version: '3'
services: 
  redis:
    image: redis
    volumes: 
      - .:/data
    networks: 
      - belakang
  python :
    image: python:2.7-slim
    working_dir: /app
    ports: 
      - 2000:80
    volumes: 
      - .:/app
    networks: 
      - belakang
    depends_on: 
      - redis
    command: bash -c "pip install --trusted-host pypi.python.org -r requirements.txt && python app.py"
networks: 
  belakang: